# Makefile.deps created Wed May 24 19:08:00 PDT 2017 by gmake
astree.o: astree.cpp astree.h auxlib.h stringset.h lyutils.h yyparse.h
lyutils.o: lyutils.cpp auxlib.h lyutils.h astree.h yyparse.h
auxlib.o: auxlib.cpp auxlib.h
stringset.o: stringset.cpp stringset.h
main.o: main.cpp auxlib.h astree.h lyutils.h yyparse.h stringset.h
yylex.o: yylex.cpp auxlib.h lyutils.h astree.h yyparse.h
yyparse.o: yyparse.cpp lyutils.h astree.h auxlib.h yyparse.h
